### ISSUE TITLE
Not supported in phpstorm version 2023.1

### ISSUE THREAD

**Issue by iestrada** [Konafets/antlers-idea#150]
After update phpstorm now the plugin is not usable.

**Comment by iestrada** [comment]
I am still having problems with the version 0.0.6 


<img width="800" alt="Captura de pantalla 2023-05-24 a la(s) 10 21 22 p  m" src="https://github.com/Konafets/antlers-idea/assets/72223/fd8ebdcb-5279-4352-84a5-492e9f5d8b2e">

**Comment by iestrada** [comment]
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[EncodingManagerImpl Document Pool[ApplicationImpl pooled thread 5],4,main] 30620540 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 313940523
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileIndexImpl.kt:180)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.isInContent(WorkspaceFileIndexImpl.kt:73)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:314)
	at com.intellij.lang.PerFileMappingsBase.getNotInHierarchy(PerFileMappingsBase.java:144)
	at com.intellij.lang.PerFileMappingsBase.getMappingInner(PerFileMappingsBase.java:136)
	at com.intellij.lang.PerFileMappingsBase.getConfiguredMapping(PerFileMappingsBase.java:105)
	at com.intellij.psi.templateLanguages.TemplateDataLanguageMappings.getMapping(TemplateDataLanguageMappings.java:46)
	at de.arrobait.antlers.file.AntlersFileType$Companion.getAssociatedFileType(AntlersFileType.kt:30)
	at de.arrobait.antlers.file.AntlersFileType$Companion.access$getAssociatedFileType(AntlersFileType.kt:16)
	at de.arrobait.antlers.file.AntlersFileType.extractCharsetFromFileContent(AntlersFileType.kt:55)
	at com.intellij.openapi.fileTypes.CharsetUtil.extractCharsetFromFileContent(CharsetUtil.java:33)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.charsetFromContentOrNull(LoadTextUtil.java:470)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.handleDocument(EncodingManagerImpl.java:131)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl$DocumentEncodingDetectRequest.run(EncodingManagerImpl.java:203)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Konafets** [comment]
Thanks for the screenshot. I installed PhpStorm 2023.1.2 and try to reproduce the error but I couldn't. Can you check which version of prettierJS you have installed?

I made a short screencast to show how it looks on my side.
![2023-05-26_17-00-33 (1)](https://github.com/Konafets/antlers-idea/assets/363363/dfac5b8a-94cb-44a1-ba79-602aef04e746)

**Comment by iestrada** [comment]
The prettier is bundled 231.9011.38

I try uninstall it but now i have this:


java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[EncodingManagerImpl Document Pool,4,main] 1186597946 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 264660557
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileIndexImpl.kt:180)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.isInContent(WorkspaceFileIndexImpl.kt:73)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:314)
	at com.intellij.lang.PerFileMappingsBase.getNotInHierarchy(PerFileMappingsBase.java:144)
	at com.intellij.lang.PerFileMappingsBase.getMappingInner(PerFileMappingsBase.java:136)
	at com.intellij.lang.PerFileMappingsBase.getConfiguredMapping(PerFileMappingsBase.java:105)
	at com.intellij.psi.templateLanguages.TemplateDataLanguageMappings.getMapping(TemplateDataLanguageMappings.java:46)
	at de.arrobait.antlers.file.AntlersFileType$Companion.getAssociatedFileType(AntlersFileType.kt:30)
	at de.arrobait.antlers.file.AntlersFileType$Companion.access$getAssociatedFileType(AntlersFileType.kt:16)
	at de.arrobait.antlers.file.AntlersFileType.extractCharsetFromFileContent(AntlersFileType.kt:55)
	at com.intellij.openapi.fileTypes.CharsetUtil.extractCharsetFromFileContent(CharsetUtil.java:33)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.charsetFromContentOrNull(LoadTextUtil.java:470)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.handleDocument(EncodingManagerImpl.java:131)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl$DocumentEncodingDetectRequest.run(EncodingManagerImpl.java:203)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Konafets** [comment]
Do you have Prettier disabled or enabled and configured?

<img width="791" alt="2023-05-26_17-34-33" src="https://github.com/Konafets/antlers-idea/assets/363363/bd5cfba9-1936-49ea-a81f-00d1cc45426c">

**Comment by iestrada** [comment]
Is Disable

<img width="991" alt="Captura de pantalla 2023-05-29 a la(s) 8 33 43 a  m" src="https://github.com/Konafets/antlers-idea/assets/72223/7c63be2e-23f4-4b0e-bb13-f0c2b8cef6aa">

**Comment by Konafets** [comment]
Can you attach the log here? You will get it from "Help | Open Log in Finder".

**Comment by iestrada** [comment]
A weird weird stuff just happend. 

I delete the log file. (Cause i was going to send you a simple one, without all my history).  I did have the plugin error. 

But after delete the log. Now the plugin is working.  Super weird.

**Comment by Konafets** [comment]
That sounds weird but glad I could help somehow :). I will close the issue for now. Open it up anytime the error comes back.
