### ISSUE TITLE
Exception in Plugin

### ISSUE THREAD

**Issue by patrikkernke** [Konafets/antlers-idea#153]
Hey @Konafets 

thank you for the hard work on this plugin. I know it is a lot of work and I appreciate it. 

I wanted to let you know, that the last days PHPStorms crashes because of the plugin. Here is the stacktrace. Maybe it helps you. It happens when selecting some text parts in the code.

```
java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
Current thread: Thread[EncodingManagerImpl Document Pool[ApplicationImpl pooled thread 3],4,main] 1027375984 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 1110023023
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1004)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.ensureIsUpToDate(WorkspaceFileIndexDataImpl.kt:127)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexDataImpl.getFileInfo(WorkspaceFileIndexDataImpl.kt:70)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.getFileInfo(WorkspaceFileIndexImpl.kt:220)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.findFileSet(WorkspaceFileIndexImpl.kt:180)
	at com.intellij.workspaceModel.core.fileIndex.impl.WorkspaceFileIndexImpl.isInContent(WorkspaceFileIndexImpl.kt:73)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.isInContent(ProjectFileIndexImpl.java:314)
	at com.intellij.lang.PerFileMappingsBase.getNotInHierarchy(PerFileMappingsBase.java:144)
	at com.intellij.lang.PerFileMappingsBase.getMappingInner(PerFileMappingsBase.java:136)
	at com.intellij.lang.PerFileMappingsBase.getConfiguredMapping(PerFileMappingsBase.java:105)
	at com.intellij.psi.templateLanguages.TemplateDataLanguageMappings.getMapping(TemplateDataLanguageMappings.java:46)
	at de.arrobait.antlers.file.AntlersFileType$Companion.getAssociatedFileType(AntlersFileType.kt:30)
	at de.arrobait.antlers.file.AntlersFileType$Companion.access$getAssociatedFileType(AntlersFileType.kt:16)
	at de.arrobait.antlers.file.AntlersFileType.extractCharsetFromFileContent(AntlersFileType.kt:55)
	at com.intellij.openapi.fileTypes.CharsetUtil.extractCharsetFromFileContent(CharsetUtil.java:33)
	at com.intellij.openapi.fileEditor.impl.LoadTextUtil.charsetFromContentOrNull(LoadTextUtil.java:470)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl.handleDocument(EncodingManagerImpl.java:131)
	at com.intellij.openapi.vfs.encoding.EncodingManagerImpl$DocumentEncodingDetectRequest.run(EncodingManagerImpl.java:203)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Konafets** [comment]
Hey @patrikkernke,

thanks for the detailed report. I'll have a look to this.

**Comment by mmodler** [comment]
Hey @Konafets 

are you still very busy or might we see a plugin update soon? ;)

**Comment by Konafets** [comment]
Hey @mmodler I am currently very busy with customer projects but looking forward to get back into fixing the issues and adding new features. Stay tuned!
